【BOTAN】TLDC TLDSP（终止） VAIAV AIAV VOTAN（终止） IKUNA（终止）
【DAHLIA】DLDSS
【FALENO】FNS FSDSS FADSS MGOLD JIMMY MFO MFT FTHT FTHTD FTK FTKD FTDSS FTBL FSFST LAX PFT ONFT
【素人CLOVER】STCV STCVS
【VERONICA】VRNC
【MAGNOLIA】MGNL
【ノースキンズ】NOSKN
【BonキュンBon】BKYNB（终止）
【カミパイ】PAIOH（终止）
【即席シロウト】INSF（终止）
【ダスッ！】NAIAD（终止）
